### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np

a=np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# 2d and 3d array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype :- creating array other than int datatype
np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [ ]:
# np.arange
a=np.arange(1,11)
print(a)
np.arange(1,50,2)

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [ ]:
# with reshape
np.arange(1,11).reshape(5,2)#(rows, column)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
  # np.random
np.random.random((3,4))

array([[0.41539421, 0.81783876, 0.40652148, 0.02007872],
       [0.71791208, 0.46642143, 0.29460129, 0.66558798],
       [0.04886549, 0.33484451, 0.9523892 , 0.43743183]])

In [ ]:
# np.linspace - linear space
np.linspace(-10,10,10) # from -10 to 10 and the number of items

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes


In [ ]:
a1 = np.arange(10) #list
a2 = np.arange(12,dtype=float).reshape(3,4) # matrix
a3 = np.arange(8).reshape(2,2,2) # tensor

In [ ]:
# ndim - dimension checker
a3.ndim

3

In [ ]:
# shape
a1.shape
a2.shape
a3.shape


(2, 2, 2)

In [ ]:
# size
print(a3.size)
a2

8


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a1.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


### Changing Datatype

In [ ]:
# astype
a3.dtype
a3.astype(np.int32) # saves memory

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scalar operations
print(a1>5)

# arithmetic
a1*a2
a1+2
a1-2
a1/2
a1**2

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# Vector operations
# arithmetic
print(a1+a2)


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


### array functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[36., 68., 83.],
       [91.,  2., 82.],
       [61., 32., 94.]])

In [ ]:
 # max/min/sum/prod
np.max(a1)

94.0

In [ ]:
np.min(a1)

In [ ]:
print(np.sum(a1)) #adds all element
print(np.prod(a1)) # multiply all

549.0
556393968119808.0


In [ ]:
# 0 -> col and 1 -> row
np.max(a1,axis = 1)

array([83., 91., 94.])

In [ ]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1,axis =0))

61.0
68.0
[22.48456261 26.98147513  5.43650214]


In [ ]:
# trignometric functions
np.sin(a1)


array([[-0.99177885, -0.89792768,  0.96836446],
       [ 0.10598751,  0.90929743,  0.31322878],
       [-0.96611777,  0.55142668, -0.24525199]])

In [ ]:
# dot product
a1 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[ 906,  960, 1014],
       [1170, 1240, 1310],
       [1434, 1520, 1606]])

In [ ]:
# log and exponents
