### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a=np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [3]:
# 2d and 3d array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype :- creating array other than int datatype
np.array([1,2,3],dtype=float)
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [6]:
# np.arange
a=np.arange(1,11)
print(a)
np.arange(1,50,2)

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [7]:
# with reshape
np.arange(1,11).reshape(5,2)#(rows, column)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
  # np.random
np.random.random((3,4))

array([[0.26206842, 0.04828922, 0.31493128, 0.84176587],
       [0.3901554 , 0.69630282, 0.67932979, 0.26860148],
       [0.54342539, 0.54755593, 0.23110282, 0.53219888]])

In [10]:
# np.linspace - linear space
np.linspace(-10,10,10) # from -10 to 10 and the number of items

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [11]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes


In [12]:
a1 = np.arange(10) #list
a2 = np.arange(12,dtype=float).reshape(3,4) # matrix
a3 = np.arange(8).reshape(2,2,2) # tensor

In [13]:
# ndim - dimension checker
a3.ndim

3

In [14]:
# shape
a1.shape
a2.shape
a3.shape


(2, 2, 2)

In [15]:
# size
print(a3.size)
a2

8


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [16]:
# itemsize
a1.itemsize

8

In [17]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


### Changing Datatype

In [18]:
# astype
a3.dtype
a3.astype(np.int32) # saves memory

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
# scalar operations
print(a1>5)

# arithmetic
a1*a2
a1+2
a1-2
a1/2
a1**2

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
# Vector operations
# arithmetic
print(a1+a2)


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


### array functions

In [23]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[33.,  4., 62.],
       [16., 96., 32.],
       [25., 72.,  7.]])

In [24]:
 # max/min/sum/prod
np.max(a1)

96.0

In [25]:
np.min(a1)

4.0

In [26]:
print(np.sum(a1)) #adds all element
print(np.prod(a1)) # multiply all

347.0
5068475596800.0


In [27]:
# 0 -> col and 1 -> row
np.max(a1,axis = 1)

array([62., 96., 72.])

In [28]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1,axis =0))

38.55555555555556
32.0
[ 6.94422222 38.96437119 22.48456261]


In [29]:
# trignometric functions
np.sin(a1)


array([[ 0.99991186, -0.7568025 , -0.7391807 ],
       [-0.28790332,  0.98358775,  0.55142668],
       [-0.13235175,  0.25382336,  0.6569866 ]])

In [30]:
# dot product
a1 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[ 906,  960, 1014],
       [1170, 1240, 1310],
       [1434, 1520, 1606]])

In [31]:
# log and exponents
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [33]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)


array([[100.,  45.,  12.],
       [ 20.,  95.,  34.]])

### Indexing and Slicing

In [32]:
# this is important for fetching items from numpy array

In [35]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [37]:
#  Indexing
a1
print(a1[-1]) # fetch the last element

9


In [44]:
print(a2)
print(a2[1,3])#(row,column)
# Note :- row and column counting starts from 0
print(a2[2,3])
print(a2[2,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
11
10


In [51]:
print(a3)

print('Fetching:',a3[1,1,0])
print('Fetching:',a3[0,0,0])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Fetching: 6
Fetching: 0


In [ ]:
# Slicing :- fetch multiple items

In [54]:
print(a1)
print(a1[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [58]:
print(a2)
print('for row',a2[0,:]) # ':' indicates all elements
print("For column:",a2[:,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
for row [0 1 2 3]
For column: [ 2  6 10]


In [76]:
print(a2[1,0:3])
print(a2[1:,1:3])
print(a2[::2,::3]) # ::2 for alternating rows
print(a2[::2,1::2])
print('break:',a2[1,::3])
print('break:',a2[1,1::])

[4 5 6]
[[ 5  6]
 [ 9 10]]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
break: [4 7]
break: [5 6 7]


In [86]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

a3[1]
print(a3[::2])
print(':',a3[0,1,:])
print(a3[1,:,1])
print(a3[2,1:,1:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
: [3 4 5]
[10 13 16]
[[22 23]
 [25 26]]


### iterating

In [91]:
print('a1:',a1)
print('a2:',a2)
print('a3:',a3)

a1: [0 1 2 3 4 5 6 7 8 9]
a2: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a3: [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [92]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [93]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [94]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [95]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape


In [96]:
# Transpose :- row to column, column to row
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [97]:
# ravel
a2.ravel() # converts into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Splitting

In [106]:
# Horizontal Splitting :- equal divison splitting
np.hsplit(a4,2)
print(np.hsplit(a4,4))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [ ]:
# Vetical Splitting


### Stacking

In [103]:
# Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4,a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [101]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical Stacking

In [104]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])