### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)[source]


In [10]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a
a=np.sort(a) # instead of sorted() because np.sort() returns the numpy array instead of list
np.sort(a)[::-1] # sorting in descending order

array([97, 96, 94, 85, 80, 73, 72, 68, 66, 63, 61, 57, 56, 21, 20])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4) # from 1 to 100, 24 items
b

array([[52,  6, 30, 61],
       [26, 80, 49, 43],
       [69,  3, 40, 26],
       [57, 82, 72, 77],
       [18,  3, 22, 31],
       [68, 25, 22, 78]])

In [5]:
np.sort(b) # row wise sorting
np.sort(b,axis =0) # columnwise sorting

array([[ 6, 30, 52, 61],
       [26, 43, 49, 80],
       [ 3, 26, 40, 69],
       [57, 72, 77, 82],
       [ 3, 18, 22, 31],
       [22, 25, 68, 78]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
# code
np.append(a,200)

array([ 20,  21,  56,  57,  61,  63,  66,  68,  72,  73,  80,  85,  94,
        96,  97, 200])

In [12]:
b

array([[52,  6, 30, 61],
       [26, 80, 49, 43],
       [69,  3, 40, 26],
       [57, 82, 72, 77],
       [18,  3, 22, 31],
       [68, 25, 22, 78]])

In [14]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[52.,  6., 30., 61.,  1.],
       [26., 80., 49., 43.,  1.],
       [69.,  3., 40., 26.,  1.],
       [57., 82., 72., 77.,  1.],
       [18.,  3., 22., 31.,  1.],
       [68., 25., 22., 78.,  1.]])

In [15]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[52.        ,  6.        , 30.        , 61.        ,  0.91943215],
       [26.        , 80.        , 49.        , 43.        ,  0.4766179 ],
       [69.        ,  3.        , 40.        , 26.        ,  0.26620461],
       [57.        , 82.        , 72.        , 77.        ,  0.33847845],
       [18.        ,  3.        , 22.        , 31.        ,  0.73819957],
       [68.        , 25.        , 22.        , 78.        ,  0.53744736]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [16]:
# code
# concetenate is generally used with tabular data i.e 2d array
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
np.concatenate((c,d),axis=0) # row wise concatenate
np.concatenate((c,d),axis=1) # column wise concatenate

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [19]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [22]:
np.unique(f)
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [23]:
# code
# EXPAND DIMENSIONS 1d to 2d, 2d to 3d, 3d to 4d
a


array([20, 21, 56, 57, 61, 63, 66, 68, 72, 73, 80, 85, 94, 96, 97])

In [25]:
np.expand_dims(a,axis=0)
np.expand_dims(a,axis=1)

array([[20, 21, 56, 57, 61, 63, 66, 68, 72, 73, 80, 85, 94, 96, 97]])