### Numpy array vs Python Lists

In [2]:
 # speed
 # list

a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)


2.7168214321136475


In [3]:
# Numpy :- same code with numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a+b
print(time.time()-start)

0.04305005073547363


In [4]:
# memory

In [5]:
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)


89095160

In [6]:
a = np.arange(10000000, dtype=np.int32)
sys.getsizeof(a)

40000112

In [7]:
# numpy is better than built in data ypes of python
# time efficient
# memory efficient
# Convinient


### Advanced Indexing

In [12]:
# Normal Indexing and Slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [16]:
# Fancy Indexing
a[[0,2,3,5]] # row
a[:,[0,2,3]] # column

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [17]:
# Boolean Indexing
# Super Important for both Numpy and Pandas
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[62, 11, 42, 50],
       [55, 19, 61, 66],
       [ 9, 23, 61, 59],
       [46, 29, 83, 11],
       [55, 91, 49, 31],
       [57, 45, 41,  6]])

In [19]:
# Find all numbers greater than 50
a > 50 # generate a boolean array according to condition
a[a>50] # Boolean Mask

array([62, 55, 61, 66, 61, 59, 83, 55, 91, 57])

In [21]:
# find out even numbers
a % 2 ==0
a[a%2==0]

array([62, 42, 50, 66, 46,  6])

In [24]:
# Find all numbers greater than 50 and are even
# bitwise & = is used to work with boolean values
# Logical and is used for logical values
a[(a>50) & (a % 2==0)]

array([62, 66])

In [25]:
# find all numbers not divisible by 7
a[a%7==0]

array([42, 91, 49])