### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)[source]


In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a
a=np.sort(a) # instead of sorted() because np.sort() returns the numpy array instead of list
np.sort(a)[::-1] # sorting in descending order

array([96, 87, 84, 77, 75, 68, 67, 67, 67, 61, 49, 49, 33, 32, 15])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4) # from 1 to 100, 24 items
b

array([[28, 17, 62, 62],
       [69, 79, 87, 98],
       [96, 67, 21, 54],
       [95, 39, 93, 53],
       [30, 94, 21, 82],
       [10, 56, 76, 83]])

In [ ]:
np.sort(b) # row wise sorting
np.sort(b,axis =0) # columnwise sorting

array([[10, 17, 21, 53],
       [28, 39, 21, 54],
       [30, 56, 62, 62],
       [69, 67, 76, 82],
       [95, 79, 87, 83],
       [96, 94, 93, 98]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 15,  32,  33,  49,  49,  61,  67,  67,  67,  68,  75,  77,  84,
        87,  96, 200])

In [ ]:
b

array([[28, 17, 62, 62],
       [69, 79, 87, 98],
       [96, 67, 21, 54],
       [95, 39, 93, 53],
       [30, 94, 21, 82],
       [10, 56, 76, 83]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[28., 17., 62., 62.,  1.],
       [69., 79., 87., 98.,  1.],
       [96., 67., 21., 54.,  1.],
       [95., 39., 93., 53.,  1.],
       [30., 94., 21., 82.,  1.],
       [10., 56., 76., 83.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[28.        , 17.        , 62.        , 62.        ,  0.43461589],
       [69.        , 79.        , 87.        , 98.        ,  0.79330487],
       [96.        , 67.        , 21.        , 54.        ,  0.75085956],
       [95.        , 39.        , 93.        , 53.        ,  0.33208722],
       [30.        , 94.        , 21.        , 82.        ,  0.51161082],
       [10.        , 56.        , 76.        , 83.        ,  0.86287779]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
# concetenate is generally used with tabular data i.e 2d array
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0) # row wise concatenate
np.concatenate((c,d),axis=1) # column wise concatenate

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [ ]:
np.unique(f)
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
# EXPAND DIMENSIONS 1d to 2d, 2d to 3d, 3d to 4d
a


array([15, 32, 33, 49, 49, 61, 67, 67, 67, 68, 75, 77, 84, 87, 96])

In [ ]:
np.expand_dims(a,axis=0)
np.expand_dims(a,axis=1)

array([[15],
       [32],
       [33],
       [49],
       [49],
       [61],
       [67],
       [67],
       [67],
       [68],
       [75],
       [77],
       [84],
       [87],
       [96]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([15, 32, 33, 49, 49, 61, 67, 67, 67, 68, 75, 77, 84, 87, 96])

In [ ]:
# find all indices with value greater than 50
np.where(a>50) # index position

(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [ ]:
# replace all values > 50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

array([15, 32, 33, 49, 49,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [ ]:
# replace even by 0s
np.where(a%2==0,0,a)

array([15,  0, 33, 49, 49, 61, 67, 67, 67,  0, 75, 77,  0, 87,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
a

array([15, 32, 33, 49, 49, 61, 67, 67, 67, 68, 75, 77, 84, 87, 96])

In [ ]:
np.argmax(a)

14

In [ ]:
np.argmax(b,axis =1) # axis=1(row), axis=0(column)

array([2, 3, 0, 0, 1, 3])

In [ ]:
print(b)

[[28 17 62 62]
 [69 79 87 98]
 [96 67 21 54]
 [95 39 93 53]
 [30 94 21 82]
 [10 56 76 83]]


In [ ]:
# np.argmin
np.argmin(a)
print(np.argmin(b,axis=0))

[5 0 2 3]


### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
np.cumsum(a)

array([ 15,  47,  80, 129, 178, 239, 306, 373, 440, 508, 583, 660, 744,
       831, 927])

In [ ]:
np.cumsum(b,axis=0)

array([[ 28,  17,  62,  62],
       [ 97,  96, 149, 160],
       [193, 163, 170, 214],
       [288, 202, 263, 267],
       [318, 296, 284, 349],
       [328, 352, 360, 432]])

In [ ]:
# np.cumprod # works same as cummilative sum but it multiplies

In [ ]:
np.cumprod(a)

array([                  15,                  480,                15840,
                     776160,             38031840,           2319942240,
               155436130080,       10414220715360,      697752787929120,
          47447189579180160,  3558539218438512000, -2693641285877850240,
       -4904939129224800768, -2454590547237979648,  4166980423378124800])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
np.percentile(a,50)

67.0

In [ ]:
np.median(a)

67.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
a

array([15, 32, 33, 49, 49, 61, 67, 67, 67, 68, 75, 77, 84, 87, 96])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 1, 0, 2, 2, 0, 5, 2, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [ ]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a

array([15, 32, 33, 49, 49, 61, 67, 67, 67, 68, 75, 77, 84, 87, 96])

In [ ]:
items = [10,20,30,40,50,60,70,80,90]
np.isin(a,items)
a[np.isin(a,items)]

array([], dtype=int64)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
print(a)
np.flip(a)

[15 32 33 49 49 61 67 67 67 68 75 77 84 87 96]


array([96, 87, 84, 77, 75, 68, 67, 67, 67, 61, 49, 49, 33, 32, 15])

In [44]:
print(b)
np.flip(b)

[[28 17 62 62]
 [69 79 87 98]
 [96 67 21 54]
 [95 39 93 53]
 [30 94 21 82]
 [10 56 76 83]]


array([[83, 76, 56, 10],
       [82, 21, 94, 30],
       [53, 93, 39, 95],
       [54, 21, 67, 96],
       [98, 87, 79, 69],
       [62, 62, 17, 28]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [45]:
# code
a

array([15, 32, 33, 49, 49, 61, 67, 67, 67, 68, 75, 77, 84, 87, 96])

In [47]:
np.put(a,[0,1],[110,530]) # permanent change in array
a

array([110, 530,  33,  49,  49,  61,  67,  67,  67,  68,  75,  77,  84,
        87,  96])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [48]:
np.delete(a,0) # index position

array([530,  33,  49,  49,  61,  67,  67,  67,  68,  75,  77,  84,  87,
        96])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [49]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.intersect1d(m,n)

array([3, 4, 5])

In [52]:
np.setdiff1d(m,n)

array([1, 2])

In [53]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [54]:
np.in1d(m,1)

array([ True, False, False, False, False])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [55]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 33, 49, 49, 61, 67, 67, 67, 68, 75, 75, 75, 75, 75])