### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)[source]


In [15]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a
a=np.sort(a) # instead of sorted() because np.sort() returns the numpy array instead of list
np.sort(a)[::-1] # sorting in descending order

array([97, 96, 95, 95, 93, 72, 46, 36, 34, 33, 29, 22, 14, 12,  4])

In [16]:
b = np.random.randint(1,100,24).reshape(6,4) # from 1 to 100, 24 items
b

array([[41, 41, 21, 66],
       [74, 61, 71, 66],
       [13, 27, 60, 29],
       [87, 17, 87, 81],
       [26, 43, 62, 18],
       [85, 99, 53, 60]])

In [17]:
np.sort(b) # row wise sorting
np.sort(b,axis =0) # columnwise sorting

array([[13, 17, 21, 18],
       [26, 27, 53, 29],
       [41, 41, 60, 60],
       [74, 43, 62, 66],
       [85, 61, 71, 66],
       [87, 99, 87, 81]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [18]:
# code
np.append(a,200)

array([  4,  12,  14,  22,  29,  33,  34,  36,  46,  72,  93,  95,  95,
        96,  97, 200])

In [19]:
b

array([[41, 41, 21, 66],
       [74, 61, 71, 66],
       [13, 27, 60, 29],
       [87, 17, 87, 81],
       [26, 43, 62, 18],
       [85, 99, 53, 60]])

In [20]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[41., 41., 21., 66.,  1.],
       [74., 61., 71., 66.,  1.],
       [13., 27., 60., 29.,  1.],
       [87., 17., 87., 81.,  1.],
       [26., 43., 62., 18.,  1.],
       [85., 99., 53., 60.,  1.]])

In [21]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[4.10000000e+01, 4.10000000e+01, 2.10000000e+01, 6.60000000e+01,
        9.17420824e-01],
       [7.40000000e+01, 6.10000000e+01, 7.10000000e+01, 6.60000000e+01,
        1.15088091e-02],
       [1.30000000e+01, 2.70000000e+01, 6.00000000e+01, 2.90000000e+01,
        2.04014955e-01],
       [8.70000000e+01, 1.70000000e+01, 8.70000000e+01, 8.10000000e+01,
        4.89428245e-03],
       [2.60000000e+01, 4.30000000e+01, 6.20000000e+01, 1.80000000e+01,
        4.45683102e-02],
       [8.50000000e+01, 9.90000000e+01, 5.30000000e+01, 6.00000000e+01,
        6.10141964e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [22]:
# code
# concetenate is generally used with tabular data i.e 2d array
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [23]:
np.concatenate((c,d),axis=0) # row wise concatenate
np.concatenate((c,d),axis=1) # column wise concatenate

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [24]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [25]:
np.unique(f)
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [26]:
# code
# EXPAND DIMENSIONS 1d to 2d, 2d to 3d, 3d to 4d
a


array([ 4, 12, 14, 22, 29, 33, 34, 36, 46, 72, 93, 95, 95, 96, 97])

In [27]:
np.expand_dims(a,axis=0)
np.expand_dims(a,axis=1)

array([[ 4],
       [12],
       [14],
       [22],
       [29],
       [33],
       [34],
       [36],
       [46],
       [72],
       [93],
       [95],
       [95],
       [96],
       [97]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [28]:
a

array([ 4, 12, 14, 22, 29, 33, 34, 36, 46, 72, 93, 95, 95, 96, 97])

In [29]:
# find all indices with value greater than 50
np.where(a>50) # index position

(array([ 9, 10, 11, 12, 13, 14]),)

In [30]:
# replace all values > 50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

array([ 4, 12, 14, 22, 29, 33, 34, 36, 46,  0,  0,  0,  0,  0,  0])

In [32]:
# replace even by 0s
np.where(a%2==0,0,a)

array([ 0,  0,  0,  0, 29, 33,  0,  0,  0,  0, 93, 95, 95,  0, 97])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [33]:
a

array([ 4, 12, 14, 22, 29, 33, 34, 36, 46, 72, 93, 95, 95, 96, 97])

In [34]:
np.argmax(a)

14

In [37]:
np.argmax(b,axis =1) # axis=1(row), axis=0(column)

array([3, 0, 2, 0, 2, 1])

In [36]:
print(b)

[[41 41 21 66]
 [74 61 71 66]
 [13 27 60 29]
 [87 17 87 81]
 [26 43 62 18]
 [85 99 53 60]]


In [40]:
# np.argmin
np.argmin(a)
print(np.argmin(b,axis=0))

[2 3 0 4]


### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [41]:
np.cumsum(a)

array([  4,  16,  30,  52,  81, 114, 148, 184, 230, 302, 395, 490, 585,
       681, 778])

In [42]:
np.cumsum(b,axis=0)

array([[ 41,  41,  21,  66],
       [115, 102,  92, 132],
       [128, 129, 152, 161],
       [215, 146, 239, 242],
       [241, 189, 301, 260],
       [326, 288, 354, 320]])

In [ ]:
# np.cumprod # works same as cummilative sum but it multiplies

In [43]:
np.cumprod(a)

array([                   4,                   48,                  672,
                      14784,               428736,             14148288,
                  481041792,          17317504512,         796605207552,
             57355574943744,     5334068469768192,   506736504627978240,
       -7200264281470722048, -8695840293935906816,  5053718878856413184])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [47]:
np.percentile(a,50)

36.0

In [46]:
np.median(a)

36.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [48]:
a

array([ 4, 12, 14, 22, 29, 33, 34, 36, 46, 72, 93, 95, 95, 96, 97])

In [50]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 3, 1, 0, 0, 1, 0, 5]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [51]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))